// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicklePlay.Data;

#nullable disable

namespace PicklePlay.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124182614_QSinit")]
    partial class QSinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PicklePlay.Models.AiSuggestedPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ReliabilityEstimate")
                        .HasColumnType("double");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.Property<string>("SuggestedUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AiSuggestedPartners");
                });

            modelBuilder.Entity("PicklePlay.Models.Award", b =>
                {
                    b.Property<int>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AwardId"));

                    b.Property<string>("AwardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("AwardType")
                        .HasColumnType("int");

                    b.Property<DateTime>("AwardedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("SetByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("AwardId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SetByUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("PicklePlay.Models.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookmarkId"));

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmark");
                });

            modelBuilder.Entity("PicklePlay.Models.Community", b =>
                {
                    b.Property<int>("CommunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CommunityId"));

                    b.Property<string>("CommunityLocation")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("community_location");

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("community_name");

                    b.Property<string>("CommunityPic")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("community_pic");

                    b.Property<string>("CommunityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("community_type");

                    b.Property<int>("CreateByUserId")
                        .HasColumnType("int")
                        .HasColumnName("createByUserId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deletion_date");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemDeletion")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_system_deletion");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastActivityDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("CommunityId");

                    b.HasIndex("CommunityName")
                        .IsUnique();

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityAnnouncement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("announcement_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hidden");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("post_date");

                    b.Property<int>("PosterUserId")
                        .HasColumnType("int")
                        .HasColumnName("poster_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("PosterUserId");

                    b.ToTable("CommunityAnnouncement");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityBlockList", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("block_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<int>("BlockByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("blockByAdminId");

                    b.Property<DateTime>("BlockDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("block_date");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text")
                        .HasColumnName("block_reason");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BlockId");

                    b.HasIndex("BlockByAdminId");

                    b.HasIndex("UserId");

                    b.HasIndex("CommunityId", "UserId")
                        .IsUnique();

                    b.ToTable("CommunityBlockList");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("SenderId");

                    b.ToTable("CommunityChatMessages");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    b.Property<DateTime?>("DateResponded")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_responded");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_sent");

                    b.Property<int>("InviteeUserId")
                        .HasColumnType("int")
                        .HasColumnName("invitee_user_id");

                    b.Property<int>("InviterUserId")
                        .HasColumnType("int")
                        .HasColumnName("inviter_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("InvitationId");

                    b.HasIndex("InviteeUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("CommunityId", "InviteeUserId", "Status")
                        .IsUnique();

                    b.ToTable("CommunityInvitation");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    b.Property<string>("CommunityRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("community_role");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("join_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("CommunityId", "UserId")
                        .IsUnique();

                    b.ToTable("CommunityMember");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("CommunityLocation")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("community_location");

                    b.Property<string>("CommunityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("communityName");

                    b.Property<string>("CommunityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("community_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("RequestByUserId")
                        .HasColumnType("int")
                        .HasColumnName("requestByUserId");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_date");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("request_status");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestByUserId");

                    b.ToTable("CommunityRequest");
                });

            modelBuilder.Entity("PicklePlay.Models.Competition", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<bool>("DoubleRR")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("doubleRR");

                    b.Property<int>("Draw")
                        .HasColumnType("int")
                        .HasColumnName("draw");

                    b.Property<bool>("DrawPublished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("drawPublished");

                    b.Property<byte>("Format")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("format");

                    b.Property<string>("MatchRule")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("matchRule");

                    b.Property<int>("NumPool")
                        .HasColumnType("int")
                        .HasColumnName("numPool");

                    b.Property<int>("StandardLoss")
                        .HasColumnType("int")
                        .HasColumnName("standardLoss");

                    b.Property<int>("StandardWin")
                        .HasColumnType("int")
                        .HasColumnName("standardWin");

                    b.Property<byte>("StandingCalculation")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("standingCalculation");

                    b.Property<bool>("ThirdPlaceMatch")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("thirdPlaceMatch");

                    b.Property<int>("TieBreakLoss")
                        .HasColumnType("int")
                        .HasColumnName("tieBreakLoss");

                    b.Property<int>("TieBreakWin")
                        .HasColumnType("int")
                        .HasColumnName("tieBreakWin");

                    b.Property<int>("WinnersPerPool")
                        .HasColumnType("int")
                        .HasColumnName("winnersPerPool");

                    b.HasKey("ScheduleId");

                    b.ToTable("competition");
                });

            modelBuilder.Entity("PicklePlay.Models.Endorsement", b =>
                {
                    b.Property<int>("EndorsementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EndorsementId"));

                    b.Property<DateTime>("DateGiven")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("Personality")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Skill")
                        .HasColumnType("int");

                    b.HasKey("EndorsementId");

                    b.HasIndex("GiverUserId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Endorsements");
                });

            modelBuilder.Entity("PicklePlay.Models.Escrow", b =>
                {
                    b.Property<int>("EscrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("escrow_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EscrowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EscrowId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Escrow");
                });

            modelBuilder.Entity("PicklePlay.Models.EscrowDispute", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dispute_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DisputeId"));

                    b.Property<string>("AdminDecision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("admin_decision");

                    b.Property<string>("AdminReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_review_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decision_date");

                    b.Property<string>("DisputeReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dispute_reason");

                    b.Property<int>("RaisedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("raisedByUserId");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("DisputeId");

                    b.HasIndex("RaisedByUserId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Escrow_Dispute");
                });

            modelBuilder.Entity("PicklePlay.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int")
                        .HasColumnName("target_user_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("UserId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("PicklePlay.Models.Friendship", b =>
                {
                    b.Property<int>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FriendshipId"));

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserOneId")
                        .HasColumnType("int");

                    b.Property<int>("UserTwoId")
                        .HasColumnType("int");

                    b.HasKey("FriendshipId");

                    b.HasIndex("UserOneId");

                    b.HasIndex("UserTwoId");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("PicklePlay.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<string>("Court")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBye")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsThirdPlaceMatch")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MatchPosition")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MatchTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NextLoserMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("NextMatchId")
                        .HasColumnType("int");

                    b.Property<string>("RoundName")
                        .HasColumnType("longtext");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Team1Id")
                        .HasColumnType("int");

                    b.Property<string>("Team1Score")
                        .HasColumnType("longtext");

                    b.Property<int?>("Team2Id")
                        .HasColumnType("int");

                    b.Property<string>("Team2Score")
                        .HasColumnType("longtext");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PicklePlay.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PicklePlay.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PicklePlay.Models.PlayerRank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RankId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoublesMatches")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastMatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("ReliabilityScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SinglesMatches")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("int");

                    b.Property<int>("UniqueCommunities")
                        .HasColumnType("int");

                    b.Property<int>("UniqueOpponents")
                        .HasColumnType("int");

                    b.Property<int>("UniquePartners")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerRanks");
                });

            modelBuilder.Entity("PicklePlay.Models.Pool", b =>
                {
                    b.Property<int>("PoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PoolId"));

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("PoolId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Pool");
                });

            modelBuilder.Entity("PicklePlay.Models.RankMatch", b =>
                {
                    b.Property<int>("RankMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RankMatchId"));

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Team1Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Team1Player2Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Team1RatingBefore")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("Team1RatingChange")
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Player1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Team2Player2Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Team2RatingBefore")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("Team2RatingChange")
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.HasKey("RankMatchId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("Team1Player1Id");

                    b.HasIndex("Team1Player2Id");

                    b.HasIndex("Team2Player1Id");

                    b.HasIndex("Team2Player2Id");

                    b.ToTable("RankMatches");
                });

            modelBuilder.Entity("PicklePlay.Models.RankMatchHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<decimal>("KFactorUsed")
                        .HasColumnType("decimal(5,3)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("RankMatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("RatingAfter")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("RatingBefore")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("RatingChange")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("ReliabilityAfter")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ReliabilityBefore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("RankMatchId");

                    b.HasIndex("UserId");

                    b.ToTable("RankMatchHistories");
                });

            modelBuilder.Entity("PicklePlay.Models.RefundRequest", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refund_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<string>("AdminDecision")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("admin_decision");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text")
                        .HasColumnName("admin_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decision_date");

                    b.Property<int>("EscrowId")
                        .HasColumnType("int")
                        .HasColumnName("escrow_id");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text")
                        .HasColumnName("refund_reason");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int")
                        .HasColumnName("reported_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("RefundId");

                    b.HasIndex("EscrowId");

                    b.HasIndex("UserId");

                    b.ToTable("Refund_Request");
                });

            modelBuilder.Entity("PicklePlay.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("AgeGroupRestriction")
                        .HasColumnType("int")
                        .HasColumnName("ageGroupRestriction");

                    b.Property<int?>("CancellationFreeze")
                        .HasColumnType("int")
                        .HasColumnName("cancellationfreeze");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    b.Property<string>("CompetitionImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("competitionImageUrl");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("EarlyBirdClose")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("earlyBirdClose");

                    b.Property<decimal?>("EarlyBirdPrice")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("earlyBirdPrice");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endTime");

                    b.Property<int>("EndorsementStatus")
                        .HasColumnType("int")
                        .HasColumnName("endorsementStatus");

                    b.Property<DateTime?>("EscrowAutoDisputeTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("escrow_auto_dispute_time");

                    b.Property<string>("EscrowStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("escrow_status");

                    b.Property<int?>("EventTag")
                        .HasColumnType("int")
                        .HasColumnName("event_tag");

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("feeAmount");

                    b.Property<int?>("FeeType")
                        .HasColumnType("int")
                        .HasColumnName("feeType");

                    b.Property<string>("GameName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gameName");

                    b.Property<int?>("GenderRestriction")
                        .HasColumnType("int")
                        .HasColumnName("genderRestriction");

                    b.Property<int?>("HostRole")
                        .HasColumnType("int")
                        .HasColumnName("hostrole");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<decimal?>("MaxRankRestriction")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("maxRankRestriction");

                    b.Property<decimal?>("MinRankRestriction")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("minRankRestriction");

                    b.Property<int?>("NumPlayer")
                        .HasColumnType("int")
                        .HasColumnName("num_player");

                    b.Property<int?>("NumTeam")
                        .HasColumnType("int")
                        .HasColumnName("num_team");

                    b.Property<int?>("ParentScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("parentScheduleId");

                    b.Property<int?>("Privacy")
                        .HasColumnType("int")
                        .HasColumnName("privacy");

                    b.Property<DateTime?>("RecurringEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recurringEndDate");

                    b.Property<int?>("RecurringWeek")
                        .HasColumnType("int")
                        .HasColumnName("recurringWeek");

                    b.Property<DateTime?>("RegClose")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("regClose");

                    b.Property<DateTime?>("RegOpen")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("regOpen");

                    b.Property<bool>("RequireOrganizerApproval")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requireOrganizerApproval");

                    b.Property<int?>("ScheduleType")
                        .HasColumnType("int")
                        .HasColumnName("schedule_type");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startTime");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalEscrowAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_escrow_amount");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("schedule");
                });

            modelBuilder.Entity("PicklePlay.Models.ScheduleChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SenderId");

                    b.ToTable("ScheduleChatMessages");
                });

            modelBuilder.Entity("PicklePlay.Models.ScheduleParticipant", b =>
                {
                    b.Property<int>("SP_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SP_Id"));

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReservedSlots")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SP_Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduleParticipants");
                });

            modelBuilder.Entity("PicklePlay.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("BracketSeed")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusForSchedule")
                        .HasColumnType("int");

                    b.Property<int?>("PoolId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamIconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TeamId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PoolId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("PicklePlay.Models.TeamInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InviteeUserId")
                        .HasColumnType("int");

                    b.Property<int>("InviterUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("InvitationId");

                    b.HasIndex("InviteeUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamInvitation");
                });

            modelBuilder.Entity("PicklePlay.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeamMemberId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMember");
                });

            modelBuilder.Entity("PicklePlay.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CardLastFour")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("card_last_four");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("EscrowId")
                        .HasColumnType("int")
                        .HasColumnName("escrow_id");

                    b.Property<DateTime?>("PaymentCompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_completed_at");

                    b.Property<string>("PaymentGatewayId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payment_gateway_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("transaction_type");

                    b.Property<int>("WalletId")
                        .HasColumnType("int")
                        .HasColumnName("wallet_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("EscrowId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("PicklePlay.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("longtext")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("EmailVerify")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("emailVerify");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phoneNo");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("profile_picture");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verification_token_expiry");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("PicklePlay.Models.UserSuspension", b =>
                {
                    b.Property<int>("SuspensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("suspension_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SuspensionId"));

                    b.Property<string>("AdminDecision")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("admin_decision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_banned");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("ReportReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_reason");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reported_by_user_id");

                    b.Property<DateTime?>("SuspensionEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("suspension_end");

                    b.Property<DateTime?>("SuspensionStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("suspension_start");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SuspensionId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Suspension");
                });

            modelBuilder.Entity("PicklePlay.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wallet_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("EscrowBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("escrow_balance");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_spent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("wallet_balance");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("PicklePlay.Models.Award", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "SetByUser")
                        .WithMany()
                        .HasForeignKey("SetByUserId");

                    b.HasOne("PicklePlay.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Schedule");

                    b.Navigation("SetByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PicklePlay.Models.Bookmark", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Community", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.Navigation("Creator");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityAnnouncement", b =>
                {
                    b.HasOne("PicklePlay.Models.Community", "Community")
                        .WithMany("Announcements")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityBlockList", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "BlockingAdmin")
                        .WithMany()
                        .HasForeignKey("BlockByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.Community", "Community")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("BlockingAdmin");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityChatMessage", b =>
                {
                    b.HasOne("PicklePlay.Models.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("PicklePlay.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("DeletedBy");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityInvitation", b =>
                {
                    b.HasOne("PicklePlay.Models.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Invitee")
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityMember", b =>
                {
                    b.HasOne("PicklePlay.Models.Community", "Community")
                        .WithMany("Memberships")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.CommunityRequest", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "RequestByUser")
                        .WithMany()
                        .HasForeignKey("RequestByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestByUser");
                });

            modelBuilder.Entity("PicklePlay.Models.Competition", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithOne("Competition")
                        .HasForeignKey("PicklePlay.Models.Competition", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PicklePlay.Models.Endorsement", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "GiverUser")
                        .WithMany()
                        .HasForeignKey("GiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiverUser");

                    b.Navigation("ReceiverUser");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PicklePlay.Models.Escrow", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany("Escrows")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.EscrowDispute", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany("EscrowDisputes")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaisedByUser");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PicklePlay.Models.Favorite", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Friendship", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "UserOne")
                        .WithMany("FriendshipsSent")
                        .HasForeignKey("UserOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "UserTwo")
                        .WithMany("FriendshipsReceived")
                        .HasForeignKey("UserTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserOne");

                    b.Navigation("UserTwo");
                });

            modelBuilder.Entity("PicklePlay.Models.Match", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "LastUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("LastUpdatedByUserId");

                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PicklePlay.Models.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PicklePlay.Models.Team", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Schedule");

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("PicklePlay.Models.Message", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PicklePlay.Models.Notification", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.PlayerRank", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithOne("Rank")
                        .HasForeignKey("PicklePlay.Models.PlayerRank", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Pool", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany("Pools")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PicklePlay.Models.RankMatch", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Team1Player1")
                        .WithMany()
                        .HasForeignKey("Team1Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Team1Player2")
                        .WithMany()
                        .HasForeignKey("Team1Player2Id");

                    b.HasOne("PicklePlay.Models.User", "Team2Player1")
                        .WithMany()
                        .HasForeignKey("Team2Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Team2Player2")
                        .WithMany()
                        .HasForeignKey("Team2Player2Id");

                    b.Navigation("Schedule");

                    b.Navigation("Team1Player1");

                    b.Navigation("Team1Player2");

                    b.Navigation("Team2Player1");

                    b.Navigation("Team2Player2");
                });

            modelBuilder.Entity("PicklePlay.Models.RankMatchHistory", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.HasOne("PicklePlay.Models.RankMatch", "RankMatch")
                        .WithMany()
                        .HasForeignKey("RankMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("RankMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.RefundRequest", b =>
                {
                    b.HasOne("PicklePlay.Models.Escrow", "Escrow")
                        .WithMany()
                        .HasForeignKey("EscrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escrow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Schedule", b =>
                {
                    b.HasOne("PicklePlay.Models.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId");

                    b.HasOne("PicklePlay.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Community");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PicklePlay.Models.ScheduleChatMessage", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeletedBy");

                    b.Navigation("Schedule");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PicklePlay.Models.ScheduleParticipant", b =>
                {
                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany("Participants")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany("ScheduleParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Team", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "Captain")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.Pool", "Pool")
                        .WithMany("Teams")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PicklePlay.Models.Schedule", "Schedule")
                        .WithMany("Teams")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Pool");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PicklePlay.Models.TeamInvitation", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "Invitee")
                        .WithMany("ReceivedTeamInvitations")
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "Inviter")
                        .WithMany("SentTeamInvitations")
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PicklePlay.Models.TeamMember", b =>
                {
                    b.HasOne("PicklePlay.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Transaction", b =>
                {
                    b.HasOne("PicklePlay.Models.Escrow", "Escrow")
                        .WithMany("Transactions")
                        .HasForeignKey("EscrowId");

                    b.HasOne("PicklePlay.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escrow");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("PicklePlay.Models.UserSuspension", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Wallet", b =>
                {
                    b.HasOne("PicklePlay.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PicklePlay.Models.Community", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("BlockedUsers");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("PicklePlay.Models.Escrow", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PicklePlay.Models.Pool", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PicklePlay.Models.Schedule", b =>
                {
                    b.Navigation("Competition");

                    b.Navigation("EscrowDisputes");

                    b.Navigation("Escrows");

                    b.Navigation("Participants");

                    b.Navigation("Pools");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PicklePlay.Models.Team", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("PicklePlay.Models.User", b =>
                {
                    b.Navigation("FriendshipsReceived");

                    b.Navigation("FriendshipsSent");

                    b.Navigation("Rank");

                    b.Navigation("ReceivedTeamInvitations");

                    b.Navigation("ScheduleParticipations");

                    b.Navigation("SentTeamInvitations");
                });

            modelBuilder.Entity("PicklePlay.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
